// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SiteGestionResaCore.Data.PcVue
{
    public partial class AICommonParameters
    {
        public int DbVersion { get; set; }
    }
}