// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SiteGestionResaCore.Data.PcVue
{
    public partial class tab_LOG_TRACA
    {
        public long Chrono { get; set; }
        public string LogList { get; set; }
        public string AssocLabel { get; set; }
        public long EvtNumber { get; set; }
        public string EvtTitle { get; set; }
        public string Name { get; set; }
        public double Value { get; set; }
        public string ValueT { get; set; }
        public short Quality { get; set; }
        public short? AlarmLevel { get; set; }
        public short? AlarmState { get; set; }
        public string UserComment { get; set; }
        public double? Threshold { get; set; }
        public double? NumParam { get; set; }
        public string TextParam { get; set; }
    }
}