// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SiteGestionResaCore.Data.PcVue
{
    public partial class tab_UA_EVAA
    {
        public long Chrono { get; set; }
        public string Name { get; set; }
        public double Value { get; set; }
        public short Quality { get; set; }
    }
}