// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SiteGestionResaCore.Data
{
    public partial class equipement
    {
        public equipement()
        {
            reservation_projet = new HashSet<reservation_projet>();
            reservation_maintenance = new HashSet<reservation_maintenance>();
			doc_essai_pgd = new HashSet<doc_essai_pgd>();
            doc_fiche_materiel = new HashSet<doc_fiche_materiel>();
        }

        public int id { get; set; }
        public string nom { get; set; }
        public int? zoneID { get; set; }
        public string numGmao { get; set; }
        public bool? mobile { get; set; }
        public string? nomTabPcVue { get; set; }

        //public string? cheminFicheMateriel { get; set; }
        //public string? cheminFicheMetrologie { get; set; }
        public string type_activites { get; set; }

        public virtual zone zone { get; set; }
        public virtual ICollection<reservation_projet> reservation_projet { get; set; }
        public virtual ICollection<reservation_maintenance> reservation_maintenance { get; set; }
        public virtual ICollection<doc_essai_pgd> doc_essai_pgd { get; set; }
		public virtual ICollection<doc_fiche_materiel> doc_fiche_materiel { get; set; }
    }
}