/*
 * website developped to manage the dairy platform STLO operations  
 * Code by Anny VIVAS, inspired from the operationnal functioning of the ancien website developped by Bruno PERRET  
 * July 2021
 * website includes code from:
 *  DotNetZip library for dealing with zip, bsip and zlib from .net 
 *  Created by: Henrik/Dino Chiesa
 * 
 *  MailKit open source library for .NET mail-client 
 *  Created by:  Jeffrey Stedfast
 * 
 *  Microsoft.AspNetCore.Identity.EntityFrameworkCore, ASP.NET Core Identity provider that uses Entity Framework Core
 *  Created by: Microsoft
 *  
 *  Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation, Runtime compilation support for Razor views and Razor pages in ASP.NET Core MVC
 *  Created by: Microsoft
 *
 *  Microsoft.EntityFrameworkCore.Design, Shared design-time components for Entity Framework Core tools
 *  Created by: Microsoft
 *
 *  Microsoft.EntityFrameworkCore.SqlServer, Microsoft SQL Server database provider for Entity Framework Core
 *  Created by: Microsoft
 *
 *  Ncrontab, NCrontab is crontab for all .NET runtimes supported by .NET Standard 1.0. It provides parsing and formatting of crontab expressions as well as calculation of occurrences of time based on a schedule expressed in the crontab format
 *  Created by: Atif Aziz
 *   
 * This projet is released under the terms of the GNU general public license GPL version 3 or later:
 * availaible here: https://www.gnu.org/licenses/gpl-3.0-standalone.html
 * 
 * Copyright (c) 2021-2024 Anny Vivas
 */


// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SiteGestionResaCore.Data
{
    public partial class essai
    {
        public essai()
        {
            reservation_projet = new HashSet<reservation_projet>();
            doc_essai_pgd = new HashSet<doc_essai_pgd>();
        }

        public int id { get; set; }
        public int projetID { get; set; }
        public int compte_userID { get; set; }
        public DateTime date_creation { get; set; }
        public int manipulateurID { get; set; }
        public string type_produit_entrant { get; set; }
        public string precision_produit { get; set; }
        public int? quantite_produit { get; set; }
        public string provenance_produit { get; set; }
        public string destination_produit { get; set; }
        public bool transport_stlo { get; set; }
        public string status_essai { get; set; }
        public string titreEssai { get; set; }
        public bool? repondu_enquete { get; set; }
        public DateTime? date_validation { get; set; }
        public bool? resa_supprime { get; set; }
        public string raison_suppression { get; set; }
        public bool? resa_refuse { get; set; }
        public string raison_refus { get; set; }
        public string confidentialite { get; set; }
        public DateTime? date_inf_confidentiel { get; set; }
        public DateTime? date_sup_confidentiel { get; set; }
        public int? enqueteId { get; set; }
        public bool? entrepot_cree { get; set; }

        public virtual utilisateur manipulateur { get; set; }
        public virtual projet projet { get; set; }
        public virtual ICollection<reservation_projet> reservation_projet { get; set; }

        public virtual enquete enquete { get; set; }
        public virtual ICollection<doc_essai_pgd> doc_essai_pgd { get; set; }
    }
}