// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SiteGestionResaCore.Data
{
    public partial class essai
    {
        public essai()
        {
            reservation_projet = new HashSet<reservation_projet>();
        }

        public int id { get; set; }
        public int projetID { get; set; }
        public string compte_userID { get; set; }
        public DateTime date_creation { get; set; }
        public int manipulateurID { get; set; }
        public string type_produit_entrant { get; set; }
        public string precision_produit { get; set; }
        public string quantite_produit { get; set; }
        public string provenance_produit { get; set; }
        public string destination_produit { get; set; }
        public bool transport_stlo { get; set; }
        public string status_essai { get; set; }
        public string commentaire { get; set; }
        public bool? repondu_enquete { get; set; }
        public DateTime? date_validation { get; set; }
        public bool? resa_supprime { get; set; }
        public string raison_suppression { get; set; }
        public bool? resa_refuse { get; set; }
        public string raison_refus { get; set; }
        public string confidentialite { get; set; }
        public DateTime? date_inf_confidentiel { get; set; }
        public DateTime? date_sup_confidentiel { get; set; }

        public virtual utilisateur manipulateur { get; set; }
        public virtual projet projet { get; set; }
        public virtual ICollection<reservation_projet> reservation_projet { get; set; }
    }
}