// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;

namespace SiteGestionResaCore.Data
{
    public partial class ld_destination
    {
        public int id { get; set; }
        public string nom_destination { get; set; }
    }
}