// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SiteGestionResaCore.Data
{
    public partial class ld_financement
    {
        public int id { get; set; }
        public string nom_financement { get; set; }
    }
}