// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SiteGestionResaCore.Data
{
    public partial class ld_provenance_produit
    {
        public int id { get; set; }
        public string nom_provenance_produit { get; set; }
    }
}