// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SiteGestionResaCore.Data
{
    public partial class organisme
    {
        public organisme()
        {
            projet = new HashSet<projet>();
            utilisateur = new HashSet<utilisateur>();
        }

        public int id { get; set; }
        public string nom_organisme { get; set; }

        public virtual ICollection<projet> projet { get; set; }
        public virtual ICollection<utilisateur> utilisateur { get; set; }
    }
}