// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SiteGestionResaCore.Data
{
    public partial class projet
    {
        public projet()
        {
            essai = new HashSet<essai>();
        }

        public int id { get; set; }
        public string titre_projet { get; set; }
        public string num_projet { get; set; }
        public string type_projet { get; set; }
        public string financement { get; set; }
        public int? organismeID { get; set; }
        public string mailRespProjet { get; set; }
        public string provenance { get; set; }
        public string description_projet { get; set; }
        public DateTime date_creation { get; set; }
        public int compte_userID { get; set; }

        public virtual organisme organisme { get; set; }
        public virtual ICollection<essai> essai { get; set; }
    }
}