// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SiteGestionResaCore.Data
{
    public partial class reservation_projet
    {
        public int id { get; set; }
        public int equipementID { get; set; }
        public int essaiID { get; set; }
        public DateTime date_debut { get; set; }
        public DateTime date_fin { get; set; }

        public virtual equipement equipement { get; set; }
        public virtual essai essai { get; set; }
    }
}