// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SiteGestionResaCore.Data
{
    public partial class zone
    {
        public zone()
        {
            equipement = new HashSet<equipement>();
        }

        public int id { get; set; }
        public string nom_zone { get; set; }

        public virtual ICollection<equipement> equipement { get; set; }
    }
}